# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)


articles = [
  {title: "The Englishman is in New York tonight!"},
  {title: "The Englishman is in Manhattan tonight!"},
  {title: "The Englishman is in Dubai tonight!"},
  {title: "The Englishman is in Italy tonight!"},
  {title: "The Englishman is in Manila tonight!"}
]


articles.each { |article|
  Article.create(
    image: "https://images.unsplash.com/photo-1531831108325-7fe9616bc780?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1964&q=80",
    title: article[:title],
    body: "
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tincidunt nisi sed justo congue, ut varius elit hendrerit. Proin varius ipsum ut elit malesuada, non dictum mi feugiat. In sem ante, bibendum sollicitudin luctus nec, porta ac mauris. Pellentesque malesuada tristique magna ut ultricies. Duis mollis rhoncus mi imperdiet tincidunt. Phasellus in enim elit. Vestibulum ac ultricies elit. Pellentesque laoreet enim et felis commodo, vel fermentum neque pretium.

Aliquam ut lacinia nisl, id convallis nunc. In hac habitasse platea dictumst. Nulla ac accumsan nisl, at facilisis dui. Vestibulum in ante semper, faucibus magna nec, egestas nunc. Aenean aliquam mauris in ex tristique pulvinar. Ut tincidunt, augue quis efficitur vestibulum, tellus ligula consequat purus, non euismod massa est at elit. Maecenas ut risus nec ex luctus fringilla vitae sed augue.

Aliquam viverra purus id accumsan interdum. Nulla eget tristique ante. Etiam tempus eu dui auctor consequat. Praesent semper eget turpis tempor interdum. Etiam porttitor dui eu neque pharetra scelerisque. Vivamus ut elementum turpis. Mauris ultricies id justo eu consequat. Sed eu sem vitae risus sodales feugiat quis in orci.

Mauris tempus ex vitae lacus dictum rutrum. Maecenas maximus, velit id venenatis dictum, magna lectus ultrices elit, dapibus lobortis sem nisl quis felis. Mauris iaculis arcu ac ex scelerisque, quis cursus nisi fringilla. Quisque vitae lacinia dui, vitae aliquam nunc. Proin fermentum ex non felis dapibus, nec maximus metus pharetra. Quisque gravida quis lacus sit amet sagittis. Aliquam quis odio ut erat ultricies auctor.

In interdum nisi magna, viverra consectetur metus commodo id. Aliquam erat volutpat. Nullam gravida tortor at lacinia consequat. Vivamus lacinia porta urna vitae ornare. Curabitur libero ex, ullamcorper pellentesque efficitur ut, mattis non justo. Sed eget euismod leo. Duis et iaculis ex, in facilisis mauris. Sed molestie lectus condimentum, vulputate tortor sed, facilisis erat. Sed varius lorem elit, at volutpat augue vulputate vitae.

Donec a purus semper velit fermentum egestas. Suspendisse auctor mauris nunc, a finibus elit elementum nec. Sed id fringilla dolor. Suspendisse eleifend nunc tellus, eget aliquet velit hendrerit non. Suspendisse potenti. Nullam sagittis, nisl at gravida eleifend, dui nunc ornare libero, sed eleifend enim tortor id enim. Duis orci augue, volutpat ac odio et, finibus hendrerit justo. Nullam sed nunc in velit vestibulum auctor et consectetur nisi. Nullam eget dui pharetra libero auctor laoreet et quis magna. Aliquam erat volutpat. In eros sapien, mattis luctus libero vitae, eleifend finibus nibh. Quisque eu auctor neque, at tristique lectus. Suspendisse sed risus sed sapien hendrerit malesuada ac quis neque. Cras molestie magna id odio tincidunt, nec pulvinar lorem tempus.

Suspendisse cursus urna sit amet est aliquet, at malesuada ipsum venenatis. Donec ornare magna id tellus tincidunt, vel facilisis lectus bibendum. Cras quis sem mi. Phasellus iaculis diam eu libero interdum ullamcorper. Maecenas auctor sagittis velit. Nunc non tellus lacinia, blandit neque eu, condimentum sem. Fusce lobortis efficitur purus egestas ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum id vehicula lacus. Integer suscipit aliquam lectus quis tempus. Mauris porttitor massa in est lacinia, vitae luctus tortor laoreet. Phasellus quis mollis diam. Vivamus vitae dapibus ligula. Etiam non lectus nec turpis luctus interdum ut a felis. Aenean tempor vulputate mauris, in lobortis justo suscipit sed. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Vivamus quis elit finibus, luctus dui eu, fermentum felis. Donec vestibulum nisi ut lacus tincidunt varius. Aliquam et metus auctor, luctus nisl eu, aliquet massa. Suspendisse tincidunt mollis nisi quis porttitor. Ut eu ullamcorper leo, ut mollis sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam erat volutpat. Mauris quis tortor quis nulla vehicula bibendum quis a velit. Nunc nisl leo, imperdiet non ex nec, euismod accumsan tortor. Curabitur bibendum eleifend metus, quis finibus ipsum hendrerit non. Maecenas maximus sapien turpis, vel finibus mi luctus sed. Cras scelerisque congue risus, et sodales arcu vulputate eu. Maecenas quam lacus, efficitur quis euismod a, facilisis ullamcorper massa.

Morbi at tempus nunc, id mattis dui. Nulla finibus accumsan arcu vel maximus. Aliquam lorem urna, vehicula at eros sit amet, maximus ornare enim. Integer eget ullamcorper leo. Nullam nisl sapien, mattis quis sodales et, semper in sem. Mauris a finibus libero. Donec imperdiet sed mauris eu pellentesque. Vestibulum congue, justo id fringilla euismod, orci dolor iaculis velit, id vulputate lectus ipsum at arcu. Quisque varius aliquet nisl ultrices posuere. In molestie, odio id blandit tincidunt, est arcu aliquam nisi, eu pellentesque mauris metus a mauris. Pellentesque mollis vehicula elit, sodales maximus tortor convallis eu. In rhoncus vel massa sed convallis. Maecenas quis ante elementum, pulvinar arcu eget, commodo dui. Nunc porta varius enim id maximus. In lectus risus, viverra quis enim quis, viverra tincidunt lacus.

Aenean in auctor leo, non aliquet enim. Quisque in diam pharetra, mattis elit vitae, elementum libero. In tristique mollis erat sed hendrerit. Phasellus molestie euismod magna a congue. Curabitur turpis urna, suscipit id pellentesque cursus, vestibulum a risus. Donec sollicitudin turpis dolor, eu tempus lorem mollis ut. Morbi sit amet ultricies ante. Integer eu leo non velit scelerisque tristique placerat at lorem. Phasellus lectus velit, semper sed lorem congue, dapibus dictum mauris. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi non vulputate sapien. Nunc id aliquet metus. Proin efficitur dui tortor, iaculis accumsan dolor fringilla ac. Suspendisse mollis eros ac erat ultricies, eget hendrerit dui mattis. Maecenas odio felis, posuere vel aliquam at, sagittis sit amet est. Mauris a nibh ante.

Integer nec augue sodales, cursus urna nec, tincidunt ante. Quisque ac quam urna. Maecenas sit amet massa lacinia, elementum enim quis, aliquam enim. Aenean at volutpat arcu, fringilla bibendum dolor. Integer ut ligula eget lectus faucibus gravida. Curabitur nec sodales metus, a facilisis arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. In ullamcorper ornare purus, et dignissim libero bibendum eu. Etiam egestas scelerisque ex, eget pretium sem blandit sit amet. Maecenas at faucibus ipsum, quis tristique orci. Vestibulum sed dui in nulla tempor commodo. Nullam a massa congue, cursus turpis quis, commodo est.

Quisque tristique elit non tellus maximus, et sagittis orci consequat. Etiam gravida est eget porttitor euismod. Mauris ac cursus ex, sed tincidunt lorem. Cras sed faucibus quam, eget condimentum velit. Duis nec tellus at ante sollicitudin rutrum. Vestibulum ultricies sagittis nisl, et vehicula ligula imperdiet vel. Mauris condimentum nisl ac mauris consequat, quis mollis arcu suscipit. Curabitur vel ante luctus, dapibus mi vitae, condimentum purus. Donec pharetra hendrerit eros, eget feugiat risus hendrerit vel. Ut venenatis ex efficitur cursus varius. Donec eleifend dui sed risus venenatis eleifend. Sed mauris mi, condimentum non fringilla at, posuere in mi. Aliquam a vulputate odio. Cras ac arcu fermentum, rutrum urna ac, porttitor sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed ac efficitur felis, eu sagittis justo.

Quisque id lectus sodales, tempus lacus nec, eleifend elit. Pellentesque consectetur nulla eget ante venenatis hendrerit. Mauris mattis accumsan nisl et iaculis. Pellentesque vel mollis metus. Aenean nec interdum ex. Aliquam congue molestie sem, finibus porta nulla venenatis in. Phasellus egestas arcu in est hendrerit tincidunt. Sed nec laoreet elit. Phasellus at diam urna. Vivamus ultrices neque urna, sit amet rhoncus nunc porttitor congue.

Fusce odio eros, cursus tincidunt arcu vitae, commodo elementum purus. Etiam mattis libero ac venenatis aliquam. Donec sed eros et ligula molestie cursus. Donec condimentum, magna in vestibulum euismod, nulla ipsum hendrerit nunc, id auctor felis lectus eu orci. Ut tempus nunc nec rhoncus elementum. Maecenas vulputate vulputate leo, at egestas nisi. Phasellus scelerisque est porttitor, placerat est non, convallis lectus. Nam elementum varius felis, nec lacinia augue hendrerit id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam scelerisque est velit, vitae congue orci luctus at. Morbi aliquam neque id velit semper, a condimentum nulla pharetra.

Vivamus vitae augue sapien. Integer id porttitor velit. Duis eleifend massa lectus, vitae egestas nisl hendrerit faucibus. Proin ac rutrum sem. Vestibulum euismod et libero nec gravida. Nullam malesuada diam vitae semper euismod. Maecenas eget lectus finibus, pulvinar purus vel, ornare urna.

Pellentesque sapien enim, tincidunt quis rhoncus non, lobortis eget nulla. Donec pharetra metus ligula. Aliquam placerat id ipsum id aliquet. Mauris in est vitae odio lacinia posuere ut ac est. Curabitur sodales sodales sodales. Aliquam nec sapien nec nulla congue volutpat. Pellentesque imperdiet leo a bibendum euismod.

Sed maximus eleifend nunc, at aliquam dui hendrerit eu. Suspendisse laoreet, velit suscipit mattis sagittis, metus orci fermentum erat, sed ultrices velit quam ut enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce interdum justo tellus, in interdum erat tristique ut. Mauris lacinia auctor ante, vel volutpat tellus semper eu. Vivamus lobortis dolor urna, et vulputate augue bibendum eu. Donec eu velit in dui pellentesque sodales eu feugiat tellus. Phasellus sed ullamcorper ipsum. Curabitur libero sapien, sagittis nec pharetra eu, blandit vestibulum leo. Donec id consequat erat, nec dapibus dui. Suspendisse porta magna in tempus elementum. Nunc id neque eu libero dapibus faucibus eu eu massa. Sed viverra non ligula sit amet hendrerit. Vivamus rutrum, eros vitae tempus iaculis, quam libero scelerisque dolor, commodo elementum neque diam sit amet velit. Mauris fermentum fringilla nibh eu placerat.

Integer a metus maximus, blandit mi et, mattis magna. Sed efficitur enim eu felis consequat maximus. Phasellus aliquet erat ac velit finibus, vitae ultricies ex venenatis. Maecenas dictum nec magna non tempus. Cras ut justo a tellus semper tempus. Proin blandit lorem lorem, eu consequat orci hendrerit quis. Curabitur euismod cursus leo a egestas. Proin a pharetra sem. Curabitur interdum convallis est, at sodales libero gravida eu.

Nullam a dui eu nisl suscipit pulvinar. Duis at justo auctor, convallis sapien a, dapibus diam. Donec fringilla non velit eget venenatis. Aenean rutrum urna nec interdum mattis. Vivamus aliquet sollicitudin mauris, et commodo erat. Pellentesque consequat lacus sed diam consectetur luctus. Sed sed metus vulputate, ultricies nisi nec, congue arcu. Cras ut nunc non sem fringilla vehicula. Mauris eget sollicitudin est. Phasellus mauris sapien, dapibus et accumsan nec, blandit sed velit. Fusce ac scelerisque metus. Maecenas pretium nunc sed metus blandit vulputate. Maecenas eget posuere ante. Mauris sit amet dui vitae lacus posuere ullamcorper.

Nam est lectus, porta non egestas at, vestibulum id ex. Suspendisse vulputate velit risus. Donec vestibulum, nisi sollicitudin eleifend venenatis, ipsum mauris finibus neque, id mollis ex purus sed elit. Vestibulum volutpat velit eu augue gravida, quis commodo nibh tempus. Nulla eu ornare risus. Sed porta est metus, et cursus justo placerat vel. In ullamcorper erat vel mauris blandit ultrices vitae vel mauris. In rhoncus lobortis massa nec feugiat. Cras bibendum libero ut magna viverra imperdiet.
    ")
}
